# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'MatWebUnB' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    # Ignore all pods project's warnings
    inhibit_all_warnings!
    
    # Pods for MatWebUnB
    pod 'SwifterSwift'
    
    target 'MatWebUnBTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'MatWebUnBUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end

